sites:
  website: https://luckyprison.com
  store: http://store.luckyprison.com
  teamspeak: ts.luckyprison.com
  twitter: https://twitter.com/luckyprison
  tumblr: https://www.tumblr.com/blog/luckyprison
  youtube: https://youtube.com/channel/UCCVbGsKU6LvsMbAhAW1Lg4A
  twitch: http://twitch.tv/luckyprison