sites:
  website: https://luckyprison.com
  store: http://store.luckyprison.com
  teamspeak: ts.luckyprison.com
  issues: https://bitbucket.org/LuckyPrison/tracker
  github: https://github.com/luckyprison
  twitter: https://twitter.com/luckyprison
  facebook: https://www.facebook.com/LuckyPrison
  tumblr: https://www.tumblr.com/blog/luckyprison
  youtube: https://youtube.com/channel/UCCVbGsKU6LvsMbAhAW1Lg4A
  twitch: http://twitch.tv/luckyprison